export const ADD_SPECIMAN = "ADD_SPECIMAN";
export const SET_SPECIMAN_SCORE = "SET_SPECIMAN_SCORE";
export const DELETE_POPULATION = "DELETE_POPULATION";
export const SET_SPECIMAN_PLAYING = "SET_SPECIMAN_PLAYING";